Resources:
  ReportsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: typeId
          AttributeType: S
        - AttributeName: accessKey
          AttributeType: S
        - AttributeName: accessToken
          AttributeType: S
        - AttributeName: linkKey
          AttributeType: S          
      KeySchema:
        - AttributeName: typeId
          KeyType: HASH
        - AttributeName: accessKey
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
      LocalSecondaryIndexes:
        - IndexName: typeId-accessToken-index
          KeySchema:
          - AttributeName: typeId
            KeyType: HASH
          - AttributeName: accessToken
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: typeId-linkKey-index
          KeySchema:
          - AttributeName: typeId
            KeyType: HASH
          - AttributeName: linkKey
            KeyType: RANGE
          Projection:
            NonKeyAttributes:
            - reportStatus
            - accessKey
            ProjectionType: INCLUDE
